### ISSUE TITLE
generate same id in same node

### ISSUE THREAD

**Issue by achilsh** [osamingo/indigo#36]
eg:
	dateTmStr := "2017-10-11 16:00:00"
	loc, _ := time.LoadLocation("Local")
	dateTime, err := time.ParseInLocation("2006-01-02 15:04:05", dateTmStr, loc)

genHandle :=  indigo.New(nil, indigo.StartTime(dateTime), indigo.MachineID(1))

idStr, err := genHandle .NextID()
//   这idstr会是相同的id
eg：
my log show this( id generation in first time)
2020/03/05 16:45:31.579 [D] [****.go:42]  new idstr: J6asGGvR1A
2020/03/05 16:45:31.579 [D] [***.go:40]  new global uniq id: J6asGGvR1A

(then generate an other id, log show the same as first one):

2020/03/05 16:45:31.579 [D] [****.go:339]  new token id: J6asGGvR1A
2020/03/05 16:45:31.579 [D] [****.go:347]  new token: J6asGGvR1A

question: 
the  implementation of unique id generator is not ok, as it produce same id in one node.
its' implementation need to check..

**Comment by achilsh** [comment]
the same id generated in twice call genHandle .NextID() is:
J6asGGvR1A
then i debase58,  the id's num is: 
126985290920230913

then i try get elapsedTime,  sequence  by  src 
"
	return uint64(sf.elapsedTime)<<(BitLenSequence+BitLenMachineID) |
		uint64(sf.sequence)<<BitLenMachineID |
		uint64(sf.machineID), nil
" 
 in  file  indigo.go, func name:  func (sf *Sonyflake) toID() (uint64, error) .

the elapsedTime value is:  2388741, 
sequence is:  1280.
look at code:

func (sf *Sonyflake) NextID() (uint64, error) {
	const maskSequence = uint16(1<<BitLenSequence - 1)

	sf.mutex.Lock()
	defer sf.mutex.Unlock()

	current := currentElapsedTime(sf.startTime)
	if sf.elapsedTime < current {
		sf.elapsedTime = current
		sf.sequence = 0
	} else { // sf.elapsedTime >= current
		sf.sequence = (sf.sequence + 1) & maskSequence
		if sf.sequence == 0 {
			sf.elapsedTime++
			overtime := sf.elapsedTime - current
			time.Sleep(sleepTime((overtime)))
		}
	}

	return sf.toID()
}

the sf.sequence  value range [0-255], but same id's sequence   is 1280. so the cal id logic has some err.
you can reparse id by yourself.
============================
my test for the same id code is this:

package main

import (
	"fmt"
	"github.com/osamingo/indigo/base58"
)

func main() {
	enc :=	base58.MustNewEncoder(base58.StdSource())
	
	retnu, err := enc.Decode("J6asGGvR1A")
	if err != nil {

	}  else {
		fmt.Println(retnu)
	}
	elapsedTime := (retnu >> 24) &  0x0000000000FFFFFF
	sequence := (retnu >> 16) & 0x000000000000FFF
	fmt.Println(elapsedTime)
	fmt.Println(sequence)

	const BitLenSequence  = 8
	 maskSequence := uint16(1<<BitLenSequence - 1)
	fmt.Println(maskSequence)
}

**Comment by achilsh** [comment]
after my test.. i test the method which you implemented, if i sleep 10*time.Millisecond, then not gen same id, but sleep less than 10ms， the same id  created...so i need append other data, eg: microsecond in 10 ms

**Comment by osamingo** [comment]
@achilsh 

Thanks for issuing! This's `sony/sonyflake` specification.
The `osamingo/indigo`'s ID is generated by an algorithm based on `sony / sonyflake`.

```
39 bits for time in units of 10 msec
                             ^^^^^^^
ref. https://github.com/sony/sonyflake
```

**Comment by osamingo** [comment]
@achilsh Did you confirm the `sony/sonyflake` document? Reopen this issue if needed.
